### ISSUE TITLE
Malformed HTML

### ISSUE THREAD

**Issue by llagerlof** [stefanbohacek/simplepagebuilder#1]
Hi! I liked your project.

I added a text and exported the zip. This is the HTML code in `index.html`:

```
<!doctype html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <link rel="stylesheet" href="./css/style.css">
          </head>
          <body><body id="ic1x"><section class="bdg-sect"><h1 class="heading">Insert title random text</h1><p class="paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p></section></body></body>
        </html>
```

Here we have a BODY tag that is inside another body tag. This is a non-valid HTML.

**Comment by stefanbohacek** [comment]
@llagerlof Thank you, and thank you for reporting this!

This is now fixed, and the exported HTML is also going to be properly formatted (using https://github.com/beautifier/js-beautify).
